version: "1"

services:
  mysql:
    image: mysql:8.0.26
    container_name: db-mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=db-ep2024
    ports:
    - 3308:3306
    networks:
    - ep2024 

networks:
  ep2024:
    name: db-ep

